# Generated by Django 6.0 on 2026-02-12 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_remove_student_classcode_remove_student_groupcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentClass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.academicclass'),
        ),
    ]
