# Generated by Django 6.0 on 2026-02-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classsubject_subject_type'),
        ('students', '0003_student_studentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.academicclass'),
        ),
    ]
