# Generated by Django 6.0 on 2026-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
