# Generated by Django 6.0 on 2026-01-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
