# Generated by Django 6.0 on 2026-01-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_breakdown'),
        ('students', '0002_remove_student_classcode_remove_student_groupcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('memo_number', models.CharField(max_length=30, unique=True)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.paymentslip'),
        ),
    ]
