# Generated by Django 6.0 on 2026-02-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentslip_payment_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentslip',
            name='total_payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
