# Generated by Django 6.0 on 2025-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('admin', 'Admin'), ('staff', 'Staff')], default='teacher', max_length=20)),
                ('teacherId', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
