# Generated by Django 6.0 on 2026-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='subject_type',
            field=models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('GROUP_COMPULSORY', 'Group compulsory'), ('ELECTIVE', 'Elective')], max_length=20),
        ),
    ]
