# Generated by Django 6.0 on 2026-03-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_classsubject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='gpa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
