# Generated by Django 6.0 on 2026-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_studentresult_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
