# Generated by Django 6.0 on 2026-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_studentresult_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='fullMarks',
            field=models.IntegerField(default=100, max_length=3),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='marks_cq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='marks_mcq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
