# Generated by Django 6.0 on 2026-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentresult_fullmarks_studentresult_marks_cq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='fullMarks',
        ),
        migrations.AddField(
            model_name='subject',
            name='fullMarks',
            field=models.IntegerField(default=100, max_length=3),
        ),
    ]
