# Generated by Django 6.0 on 2026-03-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_remove_studentresult_fullmarks_subject_fullmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='fullMarks',
            new_name='full_marks',
        ),
    ]
