# Generated by Django 6.0 on 2026-03-28 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_rename_fullmarks_subject_full_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='full_marks',
            field=models.IntegerField(default=100),
        ),
    ]
