# Generated by Django 6.0 on 2026-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_subject_parent_subject_alter_subject_full_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
